/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package odonto.kids.personal.controll.app;

import odonto.kids.personal.controll.list.LinkedList;

import static odonto.kids.personal.controll.utilities.StringUtils.join;
import static odonto.kids.personal.controll.utilities.StringUtils.split;
import static odonto.kids.personal.controll.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {
    public static void main(String[] args) {
   SpringApplication.run(App.class, args);
    }
}
