/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package odonto.kids.personal.controll.app;

import odonto.kids.personal.controll.list.LinkedList;

import static odonto.kids.personal.controll.utilities.StringUtils.join;
import static odonto.kids.personal.controll.utilities.StringUtils.split;
import static odonto.kids.personal.controll.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
