/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package odonto.kids.personal.controll.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
